== Matching, parsing and validating

.The `Production` concept
[source,cpp]
----
struct Production
{
    static constexpr auto rule = …;
    static constexpr auto whitespace = …; // optional

    static constexpr auto value = …; // optional
};
----

A `Production` is type containing a rule and optional callbacks that produce the value.
A grammar contains an entry production where parsing begins and all productions referenced by it.

TIP: It is recommended to put all productions of a grammar into a separate namespace.

By passing the entry production of the grammar to `lexy::match()`, `lexy::parse()`, or `lexy::validate()`, the production is parsed.

[discrete]
=== Matching

.`lexy/action/match.hpp`
[source,cpp]
----
namespace lexy
{
    template <typename Production, typename Input>
    constexpr bool match(const Input& input);
}
----

The function `lexy::match()` matches the `Production` on the given `input`.
If the production accepts the input, returns `true`, otherwise, returns `false`.
It will discard any values produced and does not give detailed information about why the production did not accept the input.

NOTE: A production does not necessarily need to consume the entire input for it to match.
Add `lexy::dsl::eof` to the end if the production should consume the entire input.
42
[discrete]
=== Validating

.`lexy/action/validate.hpp`
[source,cpp]
----
namespace lexy
{
    template <typename ErrorCallback>
    class validate_result
    {
    public:
        using error_callback = ErrorCallback;
        using error_type     = /* return type of the sink */;

        constexpr explicit operator bool() const noexcept
        {
            return is_success();
        }

        constexpr bool is_success() const noexcept; // <1>
        constexpr bool is_error() const noexcept; // <2>
        constexpr bool is_recovered_error() const noexcept; // <3>
        constexpr bool is_fatal_error() const noexcept; // <4>

        constexpr std::size_t error_count() const noexcept;

        constexpr const error_type& errors() const& noexcept;
        constexpr error_type&& errors() && noexcept;
    };

    template <typename Production, typename Input, typename ErrorCallback>
    constexpr auto validate(const Input& input, ErrorCallback error_callback)
        -> validate_result<ErrorCallback>;
}
----
<1> Returns `true` if no error occurred during validation.
<2> Returns `true` if at least one error occurred during validation.
<3> Returns `true` if at least one error occurred during validation, but parsing could recover after all of them.
<4> Returns `true` if at least one error occurred during validation and parsing had to cancel.

The function `lexy::validate()` validates that the `Production` matches on the given `input`.
If a parse error occurs, it will invoke the error callback (see <<Error handling>>); all errors are then returned.
It will discard any values produced.

NOTE: A production does not necessarily need to consume the entire input for it to match.
Add `lexy::dsl::eof` to the end if the production should consume the entire input.

[discrete]
=== Parsing

.`lexy/action/parse.hpp`
[source,cpp]
----
namespace lexy
{
    template <typename T, typename ErrorCallback>
    class parse_result
    {
    public:
        using value_type     = T;
        using error_callback = ErrorCallback;
        using error_type     = /* return type of the sink */;

        //=== status ===//
        constexpr explicit operator bool() const noexcept
        {
            return is_success();
        }

        constexpr bool is_success() const noexcept; // <1>
        constexpr bool is_error() const noexcept; // <2>
        constexpr bool is_recovered_error() const noexcept; // <3>
        constexpr bool is_fatal_error() const noexcept; // <4>

        //=== value ===//
        constexpr bool has_value() const noexcept; // <5>

        constexpr const T& value() const& noexcept;
        constexpr T&& value() && noexcept;

        //=== error ===//
        constexpr std::size_t error_count() const noexcept;

        constexpr const error_type& errors() const& noexcept;
        constexpr error_type&& errors() && noexcept;
    };

    template <typename Production, typename Input, typename ErrorCallback>
    constexpr auto parse(const Input& input, ErrorCallback error_callback)
        -> parse_result</* see below */, ErrorCallback>;

    template <typename Production, typename Input, typename State, typename ErrorCallback>
    constexpr auto parse(const Input& input, const State& state, ErrorCallback error_callback)
        -> parse_result</* see below */, ErrorCallback>;
}
----
<1> Returns `true` if no error occurred during parsing.
<2> Returns `true` if at least one error occurred during parsing.
<3> Returns `true` if at least one error occurred during parsing, but parsing could recover after all of them.
<4> Returns `true` if at least one error occurred during parsing and parsing had to cancel.
<5> Returns `true` if parsing could produce a value. This can only happen if there was no fatal error.

The function `lexy::parse()` parses the `Production` on the given `input`.
The return value is a `lexy::parse_result<T, ErrorCallback>`, where `T` is the return type of the `Production::value` or `Production::list` callback.
If the production accepts the input or there are only recoverable errors, invokes `Production::value` (see below) with the produced values and returns their result.
Invokes the error callback for each parse error (see <<Error handling>>) and collects the errors.

The return value on success is determined using `Production::value` depending on three cases:

* `Production::rule` does not contain a list. Then all arguments will be forwarded to `Production::value` as a callback whose result is returned.
* `Production::rule` contains a list and no other rule produces a value. Then `Production::value` will be used as sink for the list values.
  If `Production::value` is also a callback that accepts the result of the sink as argument,
  it will be invoked with the sink result and the processed result returned.
  Otherwise, the result of the sink is the final result.
* `Production::rule` contains a list and other rules produce values as well.
  Then `Production::value` will be used as sink for the list values.
  The sink result will be added to the other values in order and everything forwarded to `Production::value` as a callback.
  The callback result is then returned.

NOTE: The callback `operator>>` is useful for case 3 to create a combined callback and sink with the desired behavior.

The second overload of `lexy::parse()` allows passing an arbitrary state argument.
This state will be made available to `lexy::parse_state` (see <<Binding arguments>>) and passed to the `.sink()` of `Production::value`, if it accepts it.
That way, you can access other information (e.g. allocators for your containers) in the callbacks.

=== Error handling

Parsing errors are reported by constructing a `lexy::error` object and passing it to the error callback of `lexy::parse` and `lexy::validate` together with the `lexy::error_context`.
The error callback must either be a sink, in which case it can return an arbitrary type that represents a collection of all the errors,
or is a non-sink callback that returns `void`, in which case it will be passed to `lexy::collect()` to turn it into a sink.

The `error_type` of `lexy::validate_result` and `lexy::parse_result` will be the return type of the sink.
For a `void` returning non-sink callback it will be `std::size_t`, which is the result of `lexy::collect()`.

.Example
[%collapsible]
=====

.A `void`-returning error callback that is not a sink.
[source, cpp]
----
class ErrorCallbackVoid
{
public:
    using return_type = void;

    template <typename Production, typename Input, typename Tag>
    void operator()(const lexy::error_context<Production, Input>& context,
                           const lexy::error<lexy::input_reader<Input>, Tag>& error) const;
};
----

.A non-`void`-returning error callback that is a sink.
[source, cpp]
----
class ErrorCallbackSink
{
public:
    class Sink
    {
    public:
        using return_type = /* ... */;

        template <typename Production, typename Input, typename Tag>
        void operator()(const lexy::error_context<Production, Input>& context,
                               const lexy::error<lexy::input_reader<Input>, Tag>& error) const;

        return_type finish() &&;
    };

    Sink sink();
};
----

Of course, overloading can be used to differentiate between various error types and contexts.

=====

=== Parse Tree

.`lexy/parse_tree.hpp`
[source,cpp]
----
namespace lexy
{
    enum class traverse_event
    {
        enter,
        exit,
        leaf,
    };

    template <typename Reader, typename TokenKind = void,
              typename MemoryResource = /* default */>
    class parse_tree
    {
    public:
        class builder;

        constexpr parse_tree();
        constexpr explicit parse_tree(MemoryResource* resource);

        bool empty() const noexcept;
        void clear() noexcept;

        class node;
        class node_kind;

        node root() const noexcept; // requires: !empty()

        class traverse_range;

        traverse_range traverse(const node& n) const noexcept;
        traverse_range traverse() const noexcept;
    };

    template <typename Input, typename TokenKind = void,
              typename MemoryResource = /* default */>
    using parse_tree_for = lexy::parse_tree<input_reader<Input>, TokenKind, MemoryResource>;

    template <typename Production, typename TokenKind, typename MemoryResource, typename Input,
              typename ErrorCallback>
    auto parse_as_tree(parse_tree<input_reader<Input>, TokenKind, MemoryResource>& tree,
                       const Input& input, ErrorCallback error_callback)
      -> lexy::validate_result<ErrorCallback>;
}
----

The class `lexy::parse_tree` represents a lossless untyped syntax tree.

The function `lexy::parse_as_tree()` parses a `Production` on the given `input` and constructs a lossless parse tree from the result.
All parse errors are passed to the error callback (see <<Error handling>>) and later returned.
If a non-recoverable parse error happens, the tree will be cleared, otherwise it contains the (partial) parse tree of the input.
It will discard any values produced by parsing the rules.

The resulting parse tree will contain a parent node for each production, and leaf node for every token.
If a token is empty and has an unknown token kind, it will not be added to the parse tree.
If a production inherits from `lexy::transparent_production`, no separate node will be created;
instead all child nodes will be added to its parent.
If a production inherits from `lexy::token_production`, tokens are merged when possible:
if there are two or more tokens with the same kind directly after each other, only a single node spanning all of them will be added,
as opposed to multiple nodes for each individual token.

Traversing the tree and concatenating the lexemes of all tokens will result in the original input.

==== Manual Tree Building

[source,cpp]
----
template <typename Reader, typename TokenKind, typename MemoryResource>
class parse_tree<Reader, TokenKind, MemoryResource>::builder
{
public:
    template <typename Production>
    explicit builder(parse_tree&& tree, Production production); // <1>
    template <typename Production>
    explicit builder(Production production); // <2>

    struct production_state;

    template <typename Production>
    production_state start_production(Production production); // <3>

    void token(token_kind<TokenKind> kind,
               typename Reader::iterator begin, typename Reader::iterator end); // <4>

    void finish_production(production_state&& s); // <5>
    void backtrack_production(production_state&& s); // <6>

    parse_tree finish() &&; // <7>
};
----
<1> Create a builder that will re-use the memory of the existing `tree`.
    Its root node will be associated with the given `Production`.
<2> Same as above, but does not re-use memory.
<3> Adds a production child node as last child of the current node and activates it.
    Returns a handle that remembers the previous current node.
<4> Adds a token node to the current node.
<5> Finishes with a child production and activates its parent.
<6> Cancels the currently activated node, by deallocating it and all children.
    Activates its parent node again.
<7> Returns the finished tree.

==== Tree Node

[source,cpp]
----
template <typename Reader, typename TokenKind, typename MemoryResource>
class parse_tree<Reader, TokenKind, MemoryResource>::node_kind
{
public:
    bool is_token() const noexcept;
    bool is_production() const noexcept;

    bool is_root() const noexcept;
    bool is_token_production() const noexcept;

    const char* name() const noexcept;

    friend bool operator==(node_kind lhs, node_kind rhs);
    friend bool operator!=(node_kind lhs, node_kind rhs);

    friend bool operator==(node_kind nk, token_kind<TokenKind> tk);
    friend bool operator==(token_kind<TokenKind> tk, node_kind nk);
    friend bool operator!=(node_kind nk, token_kind<TokenKind> tk);
    friend bool operator!=(token_kind<TokenKind> tk, node_kind nk);

    template <typename Production>
    friend bool operator==(node_kind nk, Production);
    template <typename Production>
    friend bool operator==(Production p, node_kind nk);
    template <typename Production>
    friend bool operator!=(node_kind nk, Production p);
    template <typename Production>
    friend bool operator!=(Production p, node_kind nk);
};
----

The class `node_kind` stores information over the kind of node.
Nodes are either associated with a `Production` or a token rule.
The root node is always a `Production` node.

[source,cpp]
----
template <typename Reader, typename TokenKind, typename MemoryResource>
class parse_tree<Reader, TokenKind, MemoryResource>::node
{
public:
    void* address() const noexcept;

    node_kind kind() const noexcept;

    node parent() const noexcept;

    /* sized range */ children() const noexcept;

    /* range */ siblings() const noexcept;

    bool is_last_child() const noexcept;

    lexy::lexeme<Reader> lexeme() const noexcept;
    lexy::token<Reader, TokenKind> token() const noexcept;

    friend bool operator==(node lhs, node rhs) noexcept;
    friend bool operator!=(node lhs, node rhs) noexcept;
};
----

The class `node` is a reference to a node in the tree.
Two nodes are equal if and only if they point to the same node in the same tree.

===== Parent Access

[source,cpp]
----
node parent() const noexcept;
----

Returns a reference to a parent node.
For the root node, returns a reference to itself.

This operation is `O(number of siblings)`.

===== Child Access

[source,cpp]
----
class children_range
{
public:
    class iterator; // value_type = node
    class sentinel;

    iterator begin() const noexcept;
    sentinel end() const noexcept;

    bool empty() const noexcept;
    std::size_t size() const noexcept;
};

children_range children() const noexcept;
----

Returns a range object that iterates over all children of the node.
For a token node, this is always the empty range.

===== Sibling Access

[source,cpp]
----
class sibling_range
{
public:
    class iterator; // value_type = node

    iterator begin() const noexcept;
    iterator end() const noexcept;

    bool empty() const noexcept;
};

sibling_range siblings() const noexcept;
----

Returns a range object that iterates over all siblings of a node.
It begins with the sibling that is immediately following the node,
and continues until it reached the last child of the parent.
Then iteration wraps around to the first child of the parent until it ends at the original node.
The original node is not included in the sibling range.

===== Token Access

[source,cpp]
----
lexy::lexeme<Reader> lexeme() const noexcept; // <1>
lexy::token<Reader, TokenKind> token() const noexcept; // <2>
----
<1> Returns the spelling of a token node. For a production node, returns the empty lexeme.
<2> Returns the spelling and token kind of a token node; must not be called on a production node.

==== Tree Traversal

[source,cpp]
----
enum class traverse_event
{
    enter,
    exit,
    leaf,
};
----

[source,cpp]
----
class traverse_range
{
public:
    class iterator; // value_type = { traverse_event, node }

    iterator begin() const noexcept;
    iterator end() const noexcept;

    bool empty() const noexcept;
};

traverse_range traverse(const node& n) const noexcept; // <1>
traverse_range traverse() const noexcept; // <2>
----
<1> Returns a range that traverses descendants of the given node.
<2> Returns a range that traverses the root node, or an empty range if the tree is empty.

The `traverse_range` iterates over a node and all its children and their children and so on.
Its value type is a (unspecified) pair whose first member is a `lexy::traverse_event` and whose second member is a `node` reference.

For a token node, the range contains only the original node with event `leaf`.

For a production node, the range begins with the original node and event `enter`.
It then does an in-order traversal of all descendants, beginning with the children of a node.
When it reaches a token node, produces it with event `leaf`.
When it reaches a production node, produces it with event `enter`, then all its descendants recursively, and then with event `exit`.
After all descendants of the original node have been produced, finishes with the original node again and event `exit`.

.Example
[%collapsible]
=====

Prints a tree.

[source,cpp]
----
auto depth = 0;
for (auto [event, node] : tree.traverse())
{
    switch (event)
    {
    case lexy::traverse_event::enter:
        ++depth;
        indent(depth);
        print_node(node);
        break;
    case lexy::traverse_event::exit:
        --depth;
        break;

    case lexy::traverse_event::leaf:
        indent(depth);
        print_node(node);
        break;
    }
}
----
=====

NOTE: Traversing a node just does pointer chasing.
There is no allocation or recursion involved.

