= Changelog

NOTE: The project is currently still in-development and especially undocumented implementation details (such as the interface of rules) are subject to changes.
Until the first release is done, breaking changes -- but not new features -- are tracked here.

== 2021-03-21

* Changed the return type of `lexy::read_file()` (and `lexy_ext::read_file()`) to use a new `lexy::read_file_result` over `lexy::result`.
* Changed the return type of `lexy::validate()` and `lexy::parse_as_tree()` to a new `lexy::validate_result` type.
* Changed the return type of `lexy::parse()` to a new `lexy::parse_result` type.
* Removed `lexy::result`.
* An error callback that returns a non-void type must now be a sink. Use `lexy::collect<Container>(error_callback)` to create a sink that stores all results in the container. If the error callback returns void, no change is required.

== 2021-02-25

* Removed empty state from `lexy::result`. It was only added because it was useful internally, but this is no longer the case.
* Reverted optimization that merged multiple lexemes in the sink/tokens of `dsl::delimited()`.
  Tokens are instead now automatically merged by the parse tree builder if direct children of a `lexy::token_production`.
* `dsl::switch_(rule).case_()` now requires a branch of the form `token >> rule`, previously it could take an arbitrary branch.

== 2021-02-21

* Unified error interface:
  ** `.error<Tag>()` has become `.error<Tag>` (e.g. for tokens, `dsl::switch()`).
  ** `f<Tag>(...)` has become `f(...).error<Tag>` (e.g. for `dsl::require()`).
  ** `ctx.require<Tag>()` has become `ctx.require().error<Tag>`.
  ** `dsl::[partial_]combination()` now have `.missing_error<Tag>` and `.duplicate_error<Tag>` members.
* **Behavior change**: if `dsl::code_point_id` overflows, the tag is now `lexy::invalid_code_point` instead of `lexy::integer_overflow`.

== 2021-02-20

* Replaced use of `lexy::_detail::string_view` by `const char*` in all user facing functions.
  As a consequence, automatic type name now requires GCC > 8.
* Removed `lexy::make_error_location()`. It has been replaced by `lexy_ext::find_input_location()`.

== 2021-02-17

Renamed `lexy::make_buffer` to `lexy::make_buffer_from_raw`.

== 2021-02-04

Removed support for arbitrary rules as content of a `dsl::delimited()` rule, no only tokens are allowed.
Also removed support for an escape choice in the `dsl::delimited()` rule, it must be a branch now.

As a related change, the sink will now be invoked with a `lexy::lexeme` that can span multiple occurrences of the content token,
not multiple times (one lexeme per token occurrence) as it was previously.
This means that a `dsl::quoted(dsl::code_point)` rule will now invoke the sink only once giving it a `lexy::lexeme` that spans the entire content of the string literal.
Previously it was invoked once per `dsl::code_point`.

== 2021-01-11

Limited implicit conversion of `lexy::nullopt` to types that are like `std::optional` or pointers.
Replaced `lexy::dsl::nullopt` by `lexy::dsl::value_t<T>` and `lexy::dsl::opt(rule)` by `rule | lexy::dsl::value_t<T>` to keep the previous behavior of getting a default constructed object of type `T`.

== 2021-01-10

* Replaced `operator[]` and `dsl::whitespaced()` by new `dsl::whitespace` rule.
Whitespace can now be parsed manually or automatically.
+
To parse whitespace manually, replace `rule[ws]` by `rule + dsl::whitespace(rule)`,
or otherwise insert `dsl::whitespace(rule)` calls where appropriate.
See `examples/email.cpp` or `examples/xml.cpp` for an example of manual whitespace skipping.
+
To parse whitespace automatically, define a `static constexpr auto whitespace` member in the root production of the grammar.
This rule is then skipped _after_ every token.
To temporarily disable automatic whitespace skipping inside one production, inherit from `lexy::token_production`.
See `examples/tutorial.cpp` or `examples/json.cpp` for an example of automatic whitespace skipping.

* Removed support for choices in while, i.e. `dsl::while_(a | b | c)`.
This can be replaced by `dsl::loop(a | b | c | dsl::break_)`.

== 2021-01-09

* Removed `.check()` from `dsl::context_flag` and `.check_eq/lt/gt` from `dsl::context_counter` due to implementation problems.
Use `.select()` and `.compare()` instead.

* A sequence rule using `operator+` is now longer a branch.
Previously, it was a branch if it consisted of only tokens.
However, this was unimplementable in combination with automatic whitespace skipping.
+
A branch condition that is a sequence is only required if you have something like `prefix + a >> rule_a | prefix + b >> rule_b`.
Use `prefix + (a >> rule_a | b >> rule_b)` instead.

== 2021-01-08

Removed context sensitive parsing mechanism from `context.hpp` (`dsl::context_push()`, `_pop()` etc.).
Use `dsl::context_lexeme` instead: `.capture()` replaces `dsl::context_push()` and `.require()` replaces `dsl::context_pop()`.

== 2021-01-03

* Removed callback from `lexy::as_list` and `lexy::as_collection`; they're now only sink.
  `lexy::construct` can be used in most cases instead.
* Merged `::list` and `::value` callbacks from productions.
  There are three cases:
  ** A production has a `value` member only: this continues to work as before.
  ** A production has a `list` member only: just rename it to `value`. It is treated as a sink automatically when required.
  ** A production has a `list` and `value` member:
     add a `value` member that uses `sink >> callback`, where `sink` was the previous `list` value and `callback` the previous `callback`.
     This will use `sink` to construct the list then pass everything to `callback`.
* `lexy::result` now has an empty state. It is only used internally and never exposed to the user.
  As a related change, the default constructor has been removed due to unclear semantics.
  Use `lexy::result(lexy::result_error)` to restore its behavior of creating a default constructed error.

== 2020-12-26

* Replaced `Pattern` concept with a new `Token` and `Branch` concept (See #10).
A `Branch` is a rule that can make branching decision (it is required by choices and can be used as branch condition).
A `Token` is an atomic parse unit; it is also a `Branch`.
+
Most patterns (e.g. `LEXY_LIT`) are now tokens, which doesn't break anything.
Some patterns are now branches (e.g. `dsl::peek()`), which breaks in rules that now require tokens (e.g. `dsl::until()`).
The remaining patterns are now plain rules (e.g. `dsl::while_(condition >> then)`), which makes them unusable as branch conditions.
+
The patterns that are now branches:
+
--
** `dsl::error`
** `dsl::peek()` and `dsl::peek_not()`
** `condition >> then` was a pattern if `then` is a pattern, now it is always a branch
--
+
The patterns that are now plain rules:
+
--
** a sequence using `operator+` (it is still a token if all arguments are tokens, so it can be used as condition)
** a choice using `operator|`, even if all arguments are tokens (use `operator/` instead which is a token)
** `dsl::while_[one]()`, even if the argument is a token
** `dsl::times()`
** `dsl::if_()`
--
+
The following rules previously required only patterns but now require tokens:
+
--
** a minus using `operator-` (both arguments)
** `dsl::until()`
** `dsl::lookahead()`
** `dsl::escape()` (the escape character itself) and its `.capture()`
** digit separators
** automatic capturing of `dsl::delimited()`
** `lexy::make_error_location()`
--
+
If you have a breaking change because you now use a non-token rule where a token was expected, use `dsl::token()`,
which turns an arbitrary rule into a token (just like `dsl::match()` turned a rule into a pattern).

* Removed `dsl::match()`; use `dsl::token()` instead.
  If you previously had `dsl::peek(dsl::match(rule)) >> then` you can now even use `dsl::peek(rule) >> then`,
  as `dsl::peek[_not]()` have learned to support arbitrary rules.

* Removed `dsl::try_<Tag>(pattern)`.
  If `pattern` is now a token, you can use `rule.error<Tag>()` instead.
  Otherwise, use `dsl::token(pattern).error<Tag>()`.

* Removed `.capture()` on `dsl::sep(pattern)` and `dsl::trailing_sep(pattern)`.
  You can now use `dsl::sep(dsl::capture(pattern))`,
  as `dsl::capture()` is now a branch and the separators have learned to support branches.

* Removed `.zero()` and `.non_zero()` from `dsl::digit<Base>`.
  Use `dsl::zero` instead of `dsl::digit<Base>.zero()`.
  Use `dsl::digit<Base> - dsl::zero` (potentially with a nice error specified using `.error()`) instead of `dsl::digit<Base>.non_zero()`.

* Removed `dsl::success`, as it is now longer needed internally.
  It can be added back if needed.

* *Behavior change*: As part of the branch changes, `dsl::peek()`, `dsl::peek_not()` and `dsl::lookahead()` are now no-ops if not used as branch condition.
  For example, `prefix + dsl::peek(rule) + suffix` is equivalent to `prefix + suffix`.
  In most cases, this is only a change in the error message as they don't consume characters.
  Use `dsl::require()` and `dsl::prevent()` if the lookahead was intended.

* *Behavior change*: Errors in whitespace are currently not reported.
For example, if you have `/* unterminated C comment int i;` and support space and C comments as whitespace,
this would previously raise an error about the unterminated C comment.
Right now, it will try to skip the C comment, fail, and then just be done with whitespace skipping.
The error for the unterminated C comment then manifests as `expected 'int', got '/*'`.
+
This behavior is only temporary until a better solution for whitespace is implemented (see #10).

== 2020-12-22

* Removed `dsl::build_list()` and `dsl::item()`.
  They were mainly used to implement `dsl::list()`, and became unnecessary after an internal restructuring.
* Removed support for choices in lists, i.e. `dsl::list(a | b | c)`.
  This can be added back if needed.
* Removed `dsl::operator!` due to implementation problems.
  Existing uses of `dsl::peek(!rule)` can be replaced by `dsl::peek_not(rule)`;
  existing uses of `!rule >> do_sth` can be replaced using `dsl::terminator()`.

