---
layout: header
header: "lexy/dsl/alternative.hpp"
entities:
  "lexy::dsl::operator/": alternative
  "alternative": alternative
---

[#alternative]
== Token rule `lexy::dsl::operator/`

{{% interface %}}
----
namespace lexy
{
    struct exhausted_alternatives {};
}

namespace lexy::dsl
{
    constexpr _token-rule_ auto operator/(_token-rule_ auto lhs,
                                        _token-rule_ auto rhs);
}
----

[.lead]
`operator/` (alternative) is a {{% token-rule %}} that matches one of the specified tokens.

Matching::
  Tries to match `lhs` and `rhs`; consuming the longest match.
Errors::
  `lexy::exhausted_alternatives`: if neither `lhs` or `rhs` matched; at the original reader position. The rule then fails without consuming anything.
Parse tree::
  Single token node whose kind is determined by the kind of `operator/`;
  the token kinds of its individual tokens are lost.

As the result of `operator/` is itself a token rule, it can be chained.

{{% playground_example alternative "Match one of the given literals." %}}

CAUTION: For literal token rules, the implementation uses a https://en.wikipedia.org/wiki/Trie[trie] to match them efficiently.
For complex tokens the alternative rule requires backtracking.
Use {{% docref choice %}} with a branch condition as an optimization.

NOTE: Unlike {{% docref choice %}}, the ordering of rules in an alternative does not matter.
It will always consume the longest match.

