---
layout: header
header: "lexy/dsl/capture.hpp"
entities:
  "lexy::dsl::capture": capture
---

[#capture]
== Rule `lexy::dsl::capture`

{{% interface %}}
----
namespace lexy::dsl
{
    constexpr _rule_        auto capture(_rule_        auto rule);
    constexpr _branch-rule_ auto capture(_branch-rule_ auto rule);
}
----

[.lead]
`capture` is a rule that parses `rule` capturing everything it has consumed as a value.

(Branch) Parsing::
  Parses `rule` unchanged.
Errors::
  All errors raised by `rule`.
  The rule then fails if `rule` has failed.
Values::
  A {{% docref "lexy::lexeme" %}} whose range covers everything consumed by `rule`,
  followed by all values produced by `rule`.

{{% godbolt-example capture "Parse a name" %}}

{{% godbolt-example capture_whitespace "Parse a name, but disable whitespace skipping" %}}

CAUTION: If a {{% token-rule %}} is captured, the `lexy::lexeme` includes the automatic whitespace skipped after the token.
Use {{% docref "lexy::dsl::no_whitespace" %}} around the `lexy::dsl::capture()` as seen in the example above.

TIP: Use the callback {{% docref "lexy::as_string" %}} to convert the {{% docref "lexy::lexeme" %}} to a string.

