---
header: "lexy/dsl/code_point.hpp"
entities:
  "lexy::dsl::code_point": code_point
---

[.lead]
Rules for matching (specific) code points.

[#code_point]
== Token rule `lexy::dsl::code_point`

{{% interface %}}
----
namespace lexy::dsl
{
    class _code-point-dsl_ // models _token-rule_
    {
    public:
        // see below for member functions
        template <char32_t CodePoint>
        constexpr _token-rule_ lit() const;

        template <typename Predicate>
        constexpr _token-rule_ auto if_() const; // see below

        template <char32_t Low, char32_t High>
        constexpr _token-rule_ auto range() const;
    };

    constexpr _code-point-dsl_ auto code_point;
}
----

[.lead]
`code_point` is a {{% token-rule %}} that matches a single Unicode https://en.wikipedia.org/wiki/Code_point[code point].

Requires::
  The input {{% encoding %}} is ASCII, UTF-8, UTF-16, or UTF-32.
  In particular, {{% docref "lexy::default_encoding" %}} and {{% docref "lexy::byte_encoding" %}} are not supported.
Matching::
  Matches and consumes all code points that form a code point in this encoding.
  For ASCII and UTF-32, this is always a single code unit, for UTF-8, this is up to 4 code units, and for UTF-16, this is up to 2 code units.
Errors::
  {{% docref "lexy::expected_char_class" %}} (`"<encoding>.code_point"`): if the current code unit(s) do not form a valid code point; at the starting reader position.
  This includes surrogates, overlong UTF-8 sequences, or out of range code points (especially for ASCII).
  The rule then fails.

{{% playground-example code_point "Parse one code point in the inputs encoding" %}}

CAUTION: As a token rule, it matches {{% docref whitespace whitespace %}} immediately following the code point.
As such, the rule is best used in contexts where automatic whitespace skipping is disabled.

NOTE: If the input has been validated, the rule only fails if the reader is at the end of the input.

[#code_point-lit]
== Token rule `lexy::dsl::code_point.lit`

{{% interface %}}
----
template <char32_t CodePoint>
constexpr _token-rule_ lit() const;
----

[.lead]
`code_pont.lit` is a {{% token-rule %}} that matches the specific `CodePoint`.

Requires::
  * `CodePoint` is the value of a scalar code point (i.e. non-surrogate and not out of bounds).
  * The input {{% encoding %}} is ASCII, UTF-8, UTF-16, or UTF-32.
    If it is ASCII, `CodePoint` is an ASCII character.
Matching::
  Matches and consumes the code units that encode `CodePoint` in the encoding of the input.
  For ASCII and UTF-32, this is a single code unit, for UTF-8 up to four code units, and for UTF-16 up to two code units.
Errors::
  {{% docref "lexy::expected_literal" %}}: if one code unit did not compare equal or the reader reached the end of the input.
  Its `.string()` is the encoded version of `CodePoint`, its `.index()` is the index of the code unit where the mismatch/missing one occurred, and its `.position()` is the reader position where it started to match the literal.

It behaves identical to {{% docref "lexy::dsl::lit" %}} where `Str` is determined by encoding `CodePoint` in the encoding of the input.

{{% playground-example "code_point_lit" "Match a smiley face" %}}

NOTE: The caveats of {{% docref "lexy::dsl::lit" %}} regarding whitespace skipping and keywords apply here as well.

CAUTION: If the input contains an ill-formed code unit sequence, this is not checked by this rule;
it simply compares each code unit.

[#code_point-if]
== Token rule `lexy::dsl::code_point.if_`

{{% interface %}}
----
template <std::predicate<lexy::code_point> Predicate>
  requires std::is_default_constructible_v<Predicate>
constexpr _token-rule_ auto if_() const;
----

[.lead]
`code_point.if_` is a {{% token-rule %}} that matches a code point fulfilling a given predicate.

Matches::
  Matches and consumes the normal `code_point` rule.
Errors::
  * {{% docref "lexy::expected_char_class" %}} (`"<type name of Predicate>"`): if `Predicate{}(cp) == false`, where `cp` is the code point we have just consumed; at the starting reader position.
    The rule then fails.
  * All errors raised by the normal `code_point` rule. The rule then fails.

{{% playground-example code_point_if "Parse even code points only" %}}

NOTE: As the rule uses the type name of `Predicate` in the error, it does not accept a lambda as predicate, but should be called with a named type instead.

NOTE: In the future, lexy will gain support for specifying code point ranges and Unicode character classes in a more convenient way, as done for {{% docref `lexy::dsl::ascii` %}}.

CAUTION: The same caveat about {{% docref whitespace whitespace %}} as for `code_point` applies here as well.

[#code_point-range]
== Token rule `lexy::dsl::code_point.range`

{{% interface %}}
----
template <char32_t Low, char32_t High>
constexpr _token-rule_ auto range() const;
----

[.lead]
`code_point.range` is a {{% token-rule %}} that matches a code point in the range `[Low, High]`.

Matches::
  Matches and consumes the normal `code_point` rule to get a `lexy::code_point cp` and checks that `Low \<= cp \<= High`.
Errors::
  * {{% docref "lexy::expected_char_class" %}} (`"code-point.range"`):
    if the code point is not in the range; at the starting reader position.
    The rule then fails.
  * All errors raised by the normal `code_point` rule. The rule then fails.

