---
layout: header
header: "lexy/dsl/context_lexeme.hpp"
entities:
  "lexy::dsl::context_lexeme": context_lexeme
---

[#context_lexeme]
== Rule DSL `lexy::dsl::lexeme`

{{% interface %}}
----
namespace lexy::dsl
{
    struct _context_lexeme-dsl_ // note: not a rule itself
    {
        constexpr _rule_ auto create() const;

        constexpr _rule_ auto capture(_rule_ auto r) const;

        constexpr _see-below_ require(_rule_ auto r) const;
    };

    template <typename Id>
    constexpr _context_lexeme-dsl_ context_lexeme;
}
----

[.lead]
`context_lexeme` is not a rule, but a DSL for specifying rules that manipulate a string variable of the current context.

The "name" of the string variable is given by `Id`, which is an arbitrary type.
Two `context_lexeme` objects manipulate the same string variable if they are instantiated by the same type.
The "namespace" is unique per type, if a different context variable ({{% docref "lexy::dsl::context_counter" %}}, {{% docref "lexy::dsl::context_flag" %}}) uses `Id`, it refers to a different variable.

The variable is created inside the current context:
it is not accessible outside the current production, including in child production.
Once the current production finishes parsing, all context variables of it are destroyed;
it is impossible to create on that persists between different productions including multiple invocations of the same production.

{{% playground_example "context_lexeme" "Parse the same word twice" %}}

=== Rule `.create()`

{{% interface %}}
----
constexpr _rule_ auto create() const;
----

[.lead]
`.create()` returns a rule that creates the string variable.

Parsing::
  Matches everything, without consuming anything.
  As a side effect, it creates a counter with name `Id` inside the current context.
  This counter is initialized to the empty string; it's underlying type is `lexy::lexeme`.
Errors::
  None.
Values::
  None.

=== Rule `.capture()`

{{% interface %}}
----
constexpr _rule_ auto capture(_rule_ auto r) const;
----

[.lead]
`.capture()` returns a rule that set the string variable.

Requires::
  A string with the name `Id` has been created in the current context,
  i.e. `.create()` has been parsed earlier.
Parsing::
  Parses `r`.
  As a side effect, it sets the string with the name `Id` to contain everything just consumed,
  similar to {{% docref "lexy::dsl::capture" %}}.
Errors::
  All errors raised by parsing `r`.
  The rule then fails if `r` has failed.
Values::
  All errors produced by parsing `r`.

=== Rule `.require()`

{{% interface %}}
----
struct _require-dsl_
{
    template <typename Tag>
    static constexpr _rule_ auto error;
};

constexpr _require-dsl_ require(_rule_ auto r) const;
----

[.lead]
`.require()` returns a rule that errors if the string variable does not have a certain value.

Requires::
  A string with the name `Id` has been created in the current context,
  i.e. `.create()` has been parsed earlier.
Parsing::
  Parses `r` and captures it in a `lexy::lexeme`.
Errors::
  * All errors raised by parsing `r`.
    The rule then fails if `r` has failed.
  * A generic error with the specified `Tag` if the captured lexeme does not match the lexeme stored in the string with name `Id` of the current context.
    Its range covers everything captured by `r` and the rule then fails.
Values::
  None; discards all values produced by `r`.

CAUTION: `.require()` discards all values produced by `r`:
presumably they would be identical to the ones produced earlier by capturing it.

