---
header: "lexy/dsl/flags.hpp"
entities:
  "lexy::dsl::flags": "flags"
---

[#flags]
== Rule `lexy::dsl::flags`

{{% interface %}}
----
namespace lexy
{
    struct duplicate_flag {};
}

namespace lexy::dsl
{
    struct _flag-rule_ // models _rule_
    {
        template <typename Tag>
        static constexpr _rule_ auto error;
    };

    constexpr _rule_ auto flags(_symbol-rule_ flag_rule);

    template <auto Default>
    constexpr _rule_ auto flags(_symbol-rule_ flag_rule);
}
----

[.lead]
`flags` is a {{% rule %}} that parses a combination of enum flags in any order.

Requires::
  `flag_rule` is a {{% docref "lexy::dsl::symbol" %}} rule that maps strings to enum values, which do not have common bits set.
  `Default` is of the same enum type.
Parsing::
  Repeatedly matches and consumes `flag_rule` until it does not match anymore.
Errors::
  `lexy::duplicate_flag`: if a flag has already been parsed; its range covers the duplicate flag.
  This is determined by checking whether the bit set by a flag has already been set in the result `(result & flag) != 0`.
  The tag can be overridden by `.error`.
Values::
  `Default | ... | flags` where `Default` is the specified value or else a default-constructed enum, and `flags` are all the flags parsed.

{{% godbolt-example flags "Parse cv qualifiers" %}}

NOTE: The enum type does not need to overload bitwise operators; the code operators on its underlying integer type and casts back at the end.

NOTE: It is equivalent to {{% docref "lexy::dsl::partial_combination" %}} with a sink that performs a bitwise or.

