---
layout: header
header: "lexy/dsl/newline.hpp"
entities:
  "lexy::dsl::newline": newline
  "lexy::dsl::eol": eol
---

[.lead]
The `newline` and `eol` token rules.

[#newline]
== Token rule `lexy::dsl::newline`

{{% interface %}}
----
namespace lexy::dsl
{
    constexpr _token-rule_ auto newline;
}
----

[.lead]
`newline` is a {{% token-rule %}} that matches a newline.

Matching::
  Tries to match and consume {{% docref "lexy::dsl::lit" %}}`<"\r\n">` or {{% docref "lexy::dsl::lit" %}}`<"\n">`.
  Succeeds if one of them matched.
Errors::
  `lexy::expected_char_class` (`"newline"`): if they both did not match; at the starting reader position.
Parse tree::
  Single token type whose kind is the predefined `lexy::newline_token_kind`.

{{% playground-example newline "Match a newline at the end" %}}

CAUTION: As a token rule, it matches {{% docref whitespace %}} immediately following the newline.
As such, the rule is best used in contexts where automatic whitespace skipping is disabled,
or where it doesn't include newline characters.

CAUTION: Differentiate between {{% docref "lexy::dsl::ascii::newline" %}},  which matches `\r` or `\n`, and `lexy::dsl::newline`, which matches `\r\n` or `\n`!

[#eol]
== Token rule `lexy::dsl::eol`

{{% interface %}}
----
namespace lexy::dsl
{
    constexpr _token-rule_ auto eol;
}
----

[.lead]
`eol` is a {{% token-rule %}} that matches the end of a line.

Matching::
  Tries to match and consume {{% docref "lexy::dsl::lit" %}}`<"\r\n">`, {{% docref "lexy::dsl::lit" %}}`<"\n">`, or {{% docref "lexy::dsl::eof" %}}.
  Succeeds if one of them matched.
Errors::
  `lexy::expected_char_class` (`"EOF"`): if they all did not match; at the starting reader position.
Parse tree::
  Single token type whose kind is the predefined `lexy::newline_token_kind`.

{{% playground-example eol "Match a newline or EOF at the end" %}}

CAUTION: The same caveat about {{% docref whitespace %}} as for `newline` applies here as well.

