---
layout: header
header: "lexy/dsl/while.hpp"
entities:
  "lexy::dsl::while_": while_
  "lexy::dsl::while_one": while_one
  "lexy::dsl::do_while": do_while
---

[.lead]
The `while_`, `while_one`, and `do_while` rules.

[#while_]
== Rule `lexy::dsl::while_`

{{% interface %}}
----
namespace lexy::dsl
{
    consteval _rule_ auto while_(_branch-rule_ auto rule);
}
----

[.lead]
`while_` is a rule that parses the {{% branch-rule %}} `rule` as often as possible.

Requires::
  `rule` must not produce any values or set context variables that persist over loop iterations.
Parsing::
  Repeatedly tries to parse `rule`, while it does not backtrack.
Errors::
  All errors raised during branch parsing of `rule`.
Values::
  None.

`while_` can only fail, if `rule` can fail after it decided to select the branch.
It can accept the empty string if `rule` backtracks on the first iteration.

{{% playground_example while "Parse a word, which can be empty" %}}

TIP: Use {{% docref "lexy::dsl::opt_list" %}} if `rule` produces values.

WARNING: If `rule` does not consume any characters, `while_` will loop forever.

CAUTION: If {{% docref whitespace %}} skipping is enabled, `while_` will skip whitespace after every token of `rule`.

[#while_one]
== Rule `lexy::dsl::while_one`

{{% interface %}}
----
namespace lexy::dsl
{
    consteval _branch-rule_ auto while_one(_branch-rule_ auto rule)
    {
        return rule >> while_(rule);
    }
}
----

[.lead]
`while_one` is a rule that parses `rule` repeatedly, but at least once.

It is entirely equivalent to `rule >> while_(rule)`.

{{% playground_example while_one "Parse a word, which cannot be empty" %}}

TIP: Use {{% docref "lexy::dsl::list" %}} if `rule` produces values.

CAUTION: If {{% docref whitespace %}} skipping is enabled, `while_one` will skip whitespace after every token of `rule`.
Consider {{% docref "lexy::dsl::identifier" %}}, which does not do that.

[#do_while]
== Rule `lexy::dsl::do_while`

{{% interface %}}
----
namespace lexy::dsl
{
    consteval _rule_ auto do_while(_rule_ auto then, _branch-rule_ auto condition)
    {
        return then + while_(condition >> then);
    }

    consteval _branch-rule_ auto do_while(_branch-rule_ auto then,
                                        _branch-rule_ auto condition)
    {
        return then >> while_(condition >> then);
    }
}
----

[.lead]
`do_while` is a rule that parses `then` while `condition` matches, but checks `condition` after `then`.

It is entirely equivalent to `then + while_(condition >> then)` if `then` is not a branch,
and `then >> while_(condition >> then)` otherwise.

{{% playground_example do_while "Parse a list of non-empty words separated by spaces" %}}

