---
layout: single
title: "Reference"
menu:
  main:
    name: "Reference"
    weight: 2
outputs: [html, json]
---
:toc: left
:toclevels: 3
:source-highlighter: rouge

This is the reference documentation for lexy.

****
The documentation is currently in the process of being rewritten.
As such, some parts of this page are already transformed into high-level entry points with links to the actual documentation,
while others are still the full documentation inline.
****

== Infrastructure

{{% docref "lexy::code_point" %}}::
  A Unicode code point.
{{% docref "lexy::lexeme" %}}::
  A lexeme, i.e. a subrange of the input.
{{% docref "lexy::token_kind" %}} and {{% docref "lexy::token" %}}::
  Identify and store tokens, i.e. concrete realization of {{% token-rule %}}s.
{{% docref "lexy::parse_tree" %}}::
  A parse tree.
{{% docref "lexy::error" %}} and {{% docref "lexy::error_context" %}}::
  The parse errors.

== Inputs and Encodings

[source,cpp]
----
template <typename T>
concept reader = …;

template <typename T>
concept input = requires(const T& obj) {
  { obj.reader() } -> reader;
};
----

An input defines the input that will be parsed by lexy.
It has a corresponding {{% encoding %}} that controls, among other things, its character type and whether certain rules are available.
The input itself is unchanging and it produces a reader which remembers the current position of the input during parsing.

.The supported encodings:
{{% docref "lexy::default_encoding" %}}::
  An unknown single byte encoding.
{{% docref "lexy::ascii_encoding" %}}::
  ASCII
{{% docref "lexy::utf8_encoding" %}}, {{% docref "lexy::utf16_encoding" %}}, {{% docref "lexy::utf32_encoding" %}}::
  UTF-8, UTF-16, UTF-32
{{% docref "lexy::byte_encoding" %}}::
  Bytes, not text.

.The pre-defined inputs:
{{% docref "lexy::range_input" %}}::
  Use a generic iterator range as input.
{{% docref "lexy::string_input" %}} and {{% docref "lexy::zstring_input" %}}::
  Use a string as input.
{{% docref "lexy::buffer" %}}::
  Create a buffer that contains the input.
{{% docref "lexy::read_file" %}}::
  Use a file as input.
{{% docref "lexy::argv_input" %}}::
  Use the command-line arguments as input.

== The grammar DSL

[source,cpp]
----
template <typename T>
concept production = requires {
      { T::production } -> rule;
      { T::whitespace } -> rule;        // optional
      { T::value } -> callback-or-sink; // optional
};
----

The grammar is specified by _productions_: classes with a `::rule` member that specifies the {{% rule %}}.
They can optionally have a `::whitespace` member that controls {{% docref "whitespace" "automatic whitespace skipping" %}}.
Both of those are specified in a C++ DSL.
The action {{% docref "lexy::parse" %}} also needs a `::value` member that controls the value produced by parsing the production.
It is specified using callbacks, special function objects, and sinks.

link:{{< ref "grammar" >}}[`lexy/grammar.hpp`]::
  Type traits for defining and interacting with the grammar.
link:{{< ref "dsl" >}}[`lexy/dsl.hpp`]::
  The DSL for specifying parse rules.
link:{{< ref "callback" >}}[`lexy/callback.hpp`]::
  The predefined callbacks and sinks for specifying the value.

TIP: It is a recommended to put all the productions into a separate namespace.

== Actions

Actions take a grammar and an input, and do something with the grammar on that input.

{{% docref "lexy::match" %}}::
  Matches a grammar on an input and return a `true`/`false` result.
{{% docref "lexy::validate" %}}::
  Validates that a grammar matches on an input, and returns the errors if it does not.
{{% docref "lexy::parse" %}}::
  Parses a grammar on an input and returns its value.
{{% docref "lexy::parse_as_tree" %}}::
  Parses a grammar on an input and returns the parse tree.

