name: Build and Test

on: [push, pull_request]

jobs:
  docker-build:
    strategy:
      fail-fast: false
      matrix:
        image:
          - gcc10
          - gcc9
          - gcc8
          - gcc7
          - clang10
          - clang9
          - clang8
          - clang50
        build_type: [Debug, Release]
    
    runs-on: ubuntu-latest
    container:
      image: conanio/${{matrix.image}}
      options: --user root

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure
