name: Build and Test

on: [push, pull_request]

jobs:
  docker-build:
    strategy:
      matrix:
        build_type: [Debug, Release]
        image: [conanio/gcc10]
    
    runs-on: ubuntu-latest
    container:
      image: ${{matrix.image}}
      volumes: ["$GITHUB_WORKSPACE:/home/conan"]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      shell: bash
      working-directory: build/
      run: ctest -C ${{matrix.build_type}}
