name: Build and Test

on: [push, pull_request]

jobs:
  docker-build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        image:
          - conanio/gcc10
          - conanio/gcc9
          - conanio/gcc8
          - conanio/gcc7
          - conanio/clang10
          - conanio/clang9
          - conanio/clang8
          - conanio/clang5
    
    runs-on: ubuntu-latest
    container:
      image: ${{matrix.image}}
      options: --user root

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G"Ninja" -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure
